### ISSUE TITLE
Simplify navigation

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/SparkEd#224]
We could use a technique used in V3 to ease navigation and avoid having multiple pages to get to a resource.
This will probably need some bit of a re-structure but it could make the process way much easier.

**Comment by CMW1952** [comment]
I agree with this approach

**Comment by OlivierJM** [comment]
I will start working on this.

**Comment by OlivierJM** [comment]
The PR here #225 introduces an easy navigation, it combines 2 pages and uses an aggregate method to combine 2 collections into one using specified keys.
This method works well, It needs to be tested further.
