### ISSUE TITLE
replace buttons with menu in sidenav

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/SparkEd#232]
The sidenav is currently positioned on the left which is kind of an anti-design but it was good for fixing issues with the navbar, it has buttons instead of a material design of a list, it would be good if we can replace it with that. 
This will solve the alignment issue mentioned here #222

**Comment by felipebrunetti94** [comment]
Hi, question, are those the buttons ?
![image](https://user-images.githubusercontent.com/47053687/70152681-6b522700-168c-11ea-83d3-2d2089a90f2b.png)
And I didn't get how you want to move to them... could you provide a example ?

thanks

**Comment by OlivierJM** [comment]
These are http://meteor.toys/ they are only there to help during development, there are not buttons and you can hit ctlr+m(both PC and Mac)  to toggle them.

**Comment by felipebrunetti94** [comment]
Oooooh.... I see, thanks, pretty cool this meteor buttons kkk
Thanks @OlivierJM
