### ISSUE TITLE
Update Meteor

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/SparkEd#39]
Meteor will need to be updated to a recent version, we are currently running v1.6 of Meteor, and the current version is v1.8

The upgrade should be seemless with little change to how files are imported on the server.

**Comment by OlivierJM** [comment]
I will be working on updating meteor to the latest stable version.

This might need some updates with some dependencies.

**Comment by OlivierJM** [comment]
The recent will be kept on a different branch until further confirmed if on how stable that branch will be.

**Comment by OlivierJM** [comment]
@abnios If you can find time, test the branch named `update-meteor` I think it would be best to do that before that we merge with the master.

**Comment by abnios** [comment]
Okay @OlivierJM, I will do that. Thanks!

**Comment by OlivierJM** [comment]
Thanks @abnios, 

A detail of changes is indicated in this pull request here #43

**Comment by OlivierJM** [comment]
I will be closing this, re-open when there is need.

The PR was merged
