### ISSUE TITLE
Requiring Add Topic

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/SparkEd#42]
@abnios do you think it would worthy it to require to add at least one topic name when creating a unit? 

Let me know what you think on this, somehow this is linked to this issue #41

**Comment by abnios** [comment]
Hello Oliver...., I prefer topic name must not be required when creating a unit. it would be better to be optional. because someone can create subject and unit names only, and files can be uploaded to the units...

**Comment by OlivierJM** [comment]
Thanks for the feedback Abi,
I will make sure I make it optional. 
Thanks
