### ISSUE TITLE
Add a change log

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/SparkEd#74]
The online manual doc will be updated later for now, changes need to be added in the CHANGELOG.md file

**Comment by OlivierJM** [comment]
The change.log file is located here https://github.com/SparkEdUAB/SparkEd/blob/master/CHANGELOG.md

what needs to be done is adding the release notes from [here](https://github.com/SparkEdUAB/SparkEd/releases) in the change log file, these should be added version by version.

**Comment by OlivierJM** [comment]
If this is your first time contributing to opensource kindly read this section here in the [readme ](https://github.com/SparkEdUAB/SparkEd/blob/master/README.md#contribution) to help you understand  how to get started.

**Comment by Peterchama** [comment]
hello this is peter

**Comment by OlivierJM** [comment]
welcome, let me know if you have read the links above and if you are willing to work on this. 😀

**Comment by Big-Zude** [comment]
Zude here

**Comment by OlivierJM** [comment]
Kindly read the comment here and give me feedback https://github.com/SparkEdUAB/SparkEd/issues/74#issuecomment-467843016

**Comment by Peterchama** [comment]
I have read the links so far

**Comment by OlivierJM** [comment]
If you are looking for inspiration on how the change log should look check this example on react repo https://github.com/facebook/react/blob/master/CHANGELOG.md#1680-february-6-2019

**Comment by Peterchama** [comment]
Thankyou let  me read and follow  through

**Comment by OlivierJM** [comment]
I just realized that this issue is linked to this one, whichever gets fixed sooner will help close the other one. 
https://github.com/SparkEdUAB/sparked-manual/issues/17

**Comment by OlivierJM** [comment]
@Big-Zude @Peterchama I have added this basic change long up to v1.6 feel free to do almost the same for other versions from the release page.
https://github.com/SparkEdUAB/SparkEd/pull/82/commits/b43e84ff113cc3c41c27306e7a147b44705f7963

**Comment by Peterchama** [comment]
frankly speaking its not making that sense but am trying undsatand am also
installing the requided softwares

**Comment by OlivierJM** [comment]
sorry about that, actually you don't need to install anything if you only need to change [this file ](https://github.com/SparkEdUAB/SparkEd/blob/master/CHANGELOG.md)
@Peterchama what you do is, navigate to that file and click on the edit then add your changes when you are done you will see a green button down asking you to propose changes, when you properly submit I will be able to see your changes.
Try that, you don't have to install anything in this case

**Comment by Peterchama** [comment]
okay because of the links suggested I needed that

**Comment by OlivierJM** [comment]
That is a general contribution guide.

**Comment by OlivierJM** [comment]
After making changes on your fork click the pull request button as indicated in picture below 

then from there you click create pull request, add me a reviewer on the right side then I will review the changes and merge them into the master.

Thank you for the effort

![screenshot 2019-03-01 at 7 40 56 am](https://user-images.githubusercontent.com/11255454/53620005-14e62280-3bfa-11e9-92e3-9c769067c168.png)

**Comment by OlivierJM** [comment]
I will keep this open in case someone wants to modify the changelog or make it look different
