### ISSUE TITLE
update the readme

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/SparkEd#84]
Add current stats of SparkEd 

This is the feedback gotten from the Ethiopian setup
> We deployed the server and loaded more than 1500 resources. it works too perfect in office (tested with 20 hosts), we will deploy the system in a school which has more than 600 students and we will see what will happen. we will do that.  

This should be included in the readme, it can be re-phrased a little bit.

**Comment by marieram** [comment]
Can I work on this?

**Comment by OlivierJM** [comment]
Sure, go ahead with it.

**Comment by marieram** [comment]
@OlivierJM where specifically on the readme would you like me to add the blurb?

**Comment by OlivierJM** [comment]
I think it would be good to put it at the top of the readme like after the 5 line.

**Comment by OlivierJM** [comment]
Thank you @marieram
